### ISSUE TITLE
Protocol: Blind Sigs on Pedersen Commitments

### ISSUE THREAD

**Issue by nopara73** [zkSNACKs/WabiSabi#10]
In this protocol one would create blind Pedersen commitments to their desired outputs and prove the sum with rangeproofs. The underlying values would be blindly signed, thus they can be registered as outputs separately. However merging these values (eg. coin consolidating) is not figured out.

More information on Blind Signatures on messages committed in Pedersen Commitments: http://www.cs.pwr.edu.pl/hanzlik/preludium/wyniki/paper2.pdf

Another Pedersen commitment blinding scheme is described in ACL paper: https://eprint.iacr.org/2012/298.pdf

**Comment by nopara73** [comment]
Coin merging in this scheme isn't solved perfectly, although denominations can mitigate most of privacy risks.

**Comment by nopara73** [comment]
@nothingmuch @seresistvanandras I'm wondering if we'd fail with the "ideal" solution with different crypto schemes we wouldn't blindly fall back to this scheme, but rather we could explore all the blind Pedersen commitment signature schemes as there are I think 3-4 variants out there.

**Comment by seresistvanandras** [comment]
I think this Blind Signature scheme admits a simple and elegant way to merge coins at output registration phase. 

Let's assume the user has two valid signatures ![$\sigma,\sigma'$](https://render.githubusercontent.com/render/math?math=%24%5Csigma%2C%5Csigma'%24) on messages ![$m,m'$](https://render.githubusercontent.com/render/math?math=%24m%2Cm'%24). In this particular blind signature scheme, the signature actually consists of two group elements, ie. ![$\sigma=(\sigma_1,\sigma_2)$](https://render.githubusercontent.com/render/math?math=%24%5Csigma%3D(%5Csigma_1%2C%5Csigma_2)%24). The signature verification entails checking the following pairings: ![$e(\sigma_1,X_{2}Y^{m}_{2})=e(\sigma_2,P_2)$](https://render.githubusercontent.com/render/math?math=%24e(%5Csigma_1%2CX_%7B2%7DY%5E%7Bm%7D_%7B2%7D)%3De(%5Csigma_2%2CP_2)%24).

**Comment by nothingmuch** [comment]
i need to go through the algebra with fresh eyes, but this iteration seems correct to me.

as discussed on the call, ideally this should be generalized from 2 to n secret summands without revealing the intermediate sums, but even without that there is still an advantage.

for example, suppose i have 3 inputs, such that the sum of any 2 is less than my desired output amount, at input registration i can split each into multiple sub amounts.

at output registration, i would then submit at 2 or more pairs of signatures which may come from either a single input or two separate inputs (in general it'd be 1 or more, but in my example at least 2 are required because no pair of sub-amounts suffices).

so the advantage i can see to doing this is a quadratic increase in the input size for the n-partition problem[1] on the registered sub-amounts (note: this is separate from the final input/output values, and both must be addressed for privacy).

without merging, the individual sub-amounts may only originate from a *single* input of a strictly greater amount, which is a concern for small inputs if clients with larger inputs don't create small sub-amount.

therefore it seems that even just pairwise merging has some benefits despite not being ideal, since it can reduce the requirement to split inputs to small sub-amounts in order to obscure the relationship between inputs and outputs.

i also think that we can get something that is roughly equivalent to a generalization to n sub-amounts, but with interactivity, by adding support for reissuance (non-synchronous) during the input registration phase: if the ![$CB^{'}=(A^{'})^{m}(A^{'})^{m'}=(A^{'})^{(m+m')}$](https://render.githubusercontent.com/render/math?math=%24CB%5E%7B'%7D%3D(A%5E%7B'%7D)%5E%7Bm%7D(A%5E%7B'%7D)%5E%7Bm'%7D%3D(A%5E%7B'%7D)%5E%7B(m%2Bm')%7D%24) relation is proved with ![$m+m'$](https://render.githubusercontent.com/render/math?math=%24m%2Bm'%24) as a secret input (knowledge of exponent), such that this value is also equal to the committed amount (this requires a third type of ZK proof for Pedersen commitment opening, also possible with a sigma protocol).

[1] commonly referred to as "subset sum", but i am willing to die on this hill ;-) also since i'm being pedantic, some of the partitions may be the empty set

**Comment by seresistvanandras** [comment]
I think an immediate and trivial generalization would allow us to prove  a k-to-n merging, where we would leak the integers k and n. I know that this is suboptimal from a privacy point of view, however, I feel that if we also want to hide these informations then we would need significantly more complex ZKPs, which still should be quite lightweight. I'll think about it.

Anyways, I do think that 2-to-1 merging is already a huge leap forward as users themselves or software could facilitate that we would not need more types of merging. This could be achieved if users are merging/consolidating their UTXOs before entering the CoinJoin in the first place, then 2-to-1 merging should be fine. However, I agree that this blows up blockchain footprint and might require additional txs from users, which I guess we want to avoid.

**Comment by nothingmuch** [comment]
why does 2-to-1 blow up the blockchain footprint? i don't see how that matters

fwiw for reissuance what i meant is that you submit some combination of signatures, and receive a new set of signatures on an arbitrary splitting of the sum, where all amounts are blinded, i think this gets all the benefits of n-to-1 merging from a privacy point of view just with additional overhead and interactivity

**Comment by seresistvanandras** [comment]
What I meant is that, in case if we only implement 2-to-1 merging, then we force users to do some consolidation of UTXOs before sending their coins to the CoinJoin transaction. These consolidating transactions would cause some added footpring to the blockchain as these consolidations might have been done **_maybe with some more complex ZK proofs_** during output registration phase without issuing those consolidating/merging txs on the blockchain.

**Comment by nothingmuch** [comment]
doesn't a reissuance operation address that?

**Comment by seresistvanandras** [comment]
I guess so, however, my understanding was that reissuance is the devil as it introduces yet another asynchronous communication round with the coordinator. Hence, we want to avoid it as much as we can.

Is this view correct @nopara73? Or a reissuance phase is okay(ish)?

**Comment by nothingmuch** [comment]
it'd be much better to do this non-interactively, but the downsides of async communication (note: not a new phase, during input registration phase) are very minimal compared to a synchronous phase or to sub-optimal tx structure, so i think that would be a clear win even if we can't figure out a way to generalize

**Comment by nothingmuch** [comment]
assuming only pairwise merging, the example of the 3 inputs (let's say 0.5, 0.4, 0.3) required for a single output (say 1.0) might go as follows.

the specific are amounts chosen naively for clarity, to avoid i should include additional fuzzed 0 amounts. since the amounts are kept completely hidden when reissuing, the the main privacy leak is temporal, depending on how many other users have registered so far. an additional reissuance phase would categorically eliminate these leaks, but i think this is better addressed by clients to retain async properties

1. at input registration i might register my inputs to obtain 4 signatures in total by registering inputs, and reissue to obtain 2 new ones. the steps in bullet points are only partially ordered:
    - register 0.5 with blinded amounts 0.3, 0.2 receiving signatures that i then unblind as ![\sigma_{1.1}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B1.1%7D) and ![\sigma_{1.2}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B1.2%7D) [1]
    - register 0.4 with blinded amounts 0.4 for ![\sigma_{2}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B2%7D)
    - register 0.3 with blinded amount 0.3 ![\sigma_{3}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B3%7D)
    - reveal ![\sigma_{1.1}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B1.1%7D) and ![\sigma_{2}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B2%7D) to request a signature, ![\sigma_{4}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B4%7D) for amount 0.7 - while keeping this total amount hidden as described above
    - reveal ![\sigma_{3}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B3%7D) and ![\sigma_{4}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B4%7D) to obtain ![\sigma_{5}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B5%7D) for amount 1.0
2. at output registration:
    - reveal ![\sigma_{5}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B5%7D) and amount 1.0 to register my desired output
    - reveal ![\sigma_{1.2}](https://render.githubusercontent.com/render/math?math=%5Csigma_%7B1.2%7D) and amount 0.1 to register change output

[1] sorry about weird indexing notation but if i write `\sigma_{1,1}` the whitespace looks really confusing when displayed inline

**Comment by seresistvanandras** [comment]
Wow! This is quite an illustrative and nice example. So reissuing can be paralellized. That's nice!

I do think we have a k-to-n merging my point is that it is not ZK, as coordinator would know that user is merging k UTXOs to n new UTXOs. But I think, this privacy leak can be thought negligible. Can we really disregard such a privacy leak?

**Comment by nothingmuch** [comment]
i think that can be mitigated if a minimum number of signatures is always required (effectively making fuzzed 0 values mandatory)

can you explain how k-of-n follow trivially from 2-of-1? i'm not seeing it

**Comment by seresistvanandras** [comment]
1. You can parallelly convince coordinator that your k signatures are valid without revealing the underlying k messages in the same fashion as it was done in the 2-to-1 case.

2. It is also quite similar to the second step of the 2-to-1 merging but coordinator will check at the end of the protocol that ![$A^{m_1}\cdot A^{m_2}\cdot\dots\cdot A^{m_n}=A^{m_1+\dots+m_n}$](https://render.githubusercontent.com/render/math?math=%24A%5E%7Bm_1%7D%5Ccdot%20A%5E%7Bm_2%7D%5Ccdot%5Cdots%5Ccdot%20A%5E%7Bm_n%7D%3DA%5E%7Bm_1%2B%5Cdots%2Bm_n%7D%24). Users can show that all the elements on the left side are well-formed and correspond to secret messages proved in the first step with Chaum-Pedersen proofs. Right-hand side can trivially be computed by coordinator, hence verifying this equality in the target group of the pairing.

**Comment by nothingmuch** [comment]
thanks! the Chaum-Pedersen proof is what failed to click, but i think this makes sense now.

so i think with this we have something that's pretty complete: arbitrary amounts, ability to change output amounts after input registration. i really like that double spending prevention is much simpler than the ideas we discussed in the context of a signature homomorphism based approach.

the main downsides:

1. requires more interaction than ideal case of offline unlinkable merging
2. signature algorithm requires pairing so this introduces some less standard assumptions (mainly a marketing concern, since a crypto break shouldn't result in more than a DoS vector) and higher implementation burden
3. not misuse resistant because merging is not fully ZK (bad client implementation of reissuance may result in privacy leaks)

which suggests these are the next problems to work on, with solutions being more of a nice to have:

1. can we make reissuance non interactive? (aside: maybe we want to to look at some of the impossibility results on transferable e-cash?)
2. can we realize the nice signature properties without a pairing function?

**Comment by seresistvanandras** [comment]
> 1. requires more interaction than ideal case of offline unlinkable merging

Maybe fully ZK offline unlinkable merging could be achieved with more advanced ZKP techniques?
> 2. signature algorithm requires pairing so this introduces some less standard assumptions (mainly a marketing concern, since a crypto break shouldn't result in more than a DoS vector) and higher implementation burden

I wanted to work with a blind signature scheme which can sign messages in a Pedersen-commitment as in that case we have coin merging for free essentially. The other paper which achieves this is by [Georg Fuchsbauer et al.](https://eprint.iacr.org/2015/626.pdf) To me it seems that without pairings we cannot achieve our desired goals. 
> 3. not misuse resistant because merging is not fully ZK (bad client implementation of reissuance may result in privacy leaks)

Audits (cryptographic and implementation) will be inevitable.
> 
> which suggests these are the next problems to work on, with solutions being more of a nice to have:
> 2. can we realize the nice signature properties without a pairing function?

We should love pairings! :)

**Comment by nothingmuch** [comment]
> Maybe fully ZK offline unlinkable merging could be achieved with more advanced ZKP techniques?

to make sure we're talking about the same thing - for sure it's possible to achieve with different means (e.g. the overkill approach described in #13, or maybe with some of the divisible e-cash work) - am i correctly understanding that only mean using the same general approach as here, namely blind signatures on homomorphic ammount commitments, double spending by revealing unblinded signatures, and no "heavy" ZKP techniques like zkSNARKs right?

> I wanted to work with a blind signature scheme which can sign messages in a Pedersen-commitment as in that case we have coin merging for free essentially. The other paper which achieves this is by [Georg Fuchsbauer et al.](https://eprint.iacr.org/2015/626.pdf) To me it seems that without pairings we cannot achieve our desired goals.

I think we might also look more closely at the signature scheme described in the Anonymous Credentials Light paper, as noted by @nopara73 above

> Audits (cryptographic and implementation) will be inevitable.

i think it's a relatively minor issue, but it'd be nice to be able to rule out the possibility, especially since this privacy leak is at a higher level than the crypto, so i suspect people are more likely to modify client behaviour

> We should love pairings! :)

i do, pairing crypto is beautiful, and that for this application the fact that it's still considered less conservative is not even a real issue, but i'm still not sure it's the most pragmatic choice...

mainly i'm concerned about the implementation challenges. if with a bit more protocol design work we can realize something similar on top of secp256k1, even something a bit less elegant, then the barrier to implementing this protocol (in C# but also more widely in the bitcoin ecosystem) will be reduced, which i think is a very important consideration. secondly, there's the the "marketing"/perceptions

**Comment by seresistvanandras** [comment]
I do think that the Blind Sig on Pedersen Commitment scheme will be the most performant we can come up with most likely. 

My intuition is that this problem cannot be solved without pairings. We essentially have two options.

1. Blind Sig scheme without pairing
Most likely the hash function  of the blind sig scheme will not support algebraic statements, hence we would need to use zkSNARKs for proving relations for Keccak, SHA256 pre-images....hence at the end of the day we would need quite-heavy zkS[N/T]ARK magic.

2. Blind Sig scheme on homomorphic commitments
We know two schemes so far, both of them rely on pairings.

**Comment by nothingmuch** [comment]
the ACL paper's signature scheme on Pederson commitments that does not rely on pairings and allows single use credentials in their construction, see sections 3-4

**Comment by seresistvanandras** [comment]
Hmmm...woah! Interesting, thanks! Gotta have a look at it and see if we can build coin merging on top of it!

**Comment by nothingmuch** [comment]
for the record, again @jonasnick deserves all the credit for these insights, see the wasabi research club https://www.youtube.com/watch?v=pgErjQSQQsg

**Comment by nopara73** [comment]
https://github.com/zkSNACKs/WabiSabi/issues/30
