### ISSUE TITLE
Protocol: ACL based

### ISSUE THREAD

**Issue by nothingmuch** [zkSNACKs/WabiSabi#16]
Mostly copypasta of #15, but with concrete signature scheme. This protocol is based on the paper: [Anonymous Credentials Light (ACL)](https://cs.brown.edu/people/fbaldimt/papers/CCS13.pdf) by Foteini Baldimtsi and Anna Lysyanskaya.

# Amount Splitting

User has UTXO with value ![v](https://render.githubusercontent.com/render/math?math=v) and wants to split it into outputs with values ![v_1](https://render.githubusercontent.com/render/math?math=v_1) and ![v_2](https://render.githubusercontent.com/render/math?math=v_2) such that ![v = v_1 + v_2](https://render.githubusercontent.com/render/math?math=v%20%3D%20v_1%20%2B%20v_2).

## Input Registration

User creates ![n](https://render.githubusercontent.com/render/math?math=n) Pedersen Commitments: ![C_1 = C(v_1, r_1), C_2 = C(v_2, r_2), C_3 = C(v_3, r_3), C_4 = C(v_4, r_4), \dots,  C_n = C(v_n, r_n,)](https://render.githubusercontent.com/render/math?math=C_1%20%3D%20C(v_1%2C%20r_1)%2C%20C_2%20%3D%20C(v_2%2C%20r_2)%2C%20C_3%20%3D%20C(v_3%2C%20r_3)%2C%20C_4%20%3D%20C(v_4%2C%20r_4)%2C%20%5Cdots%2C%20%20C_n%20%3D%20C(v_n%2C%20r_n%2C)) where ![\forall i \in 3 \dots n: v_i = 0](https://render.githubusercontent.com/render/math?math=%5Cforall%20i%20%5Cin%203%20%5Cdots%20n%3A%20v_i%20%3D%200). The ![v_i](https://render.githubusercontent.com/render/math?math=v_i) terms correspond to a single attribute ![L_0](https://render.githubusercontent.com/render/math?math=L_0) in an ACL signature with an empty message, with a range proofs for each.

The user also needs to prove the sum of the commitments - I think this can just be done revealing ![\sum_{i=1}^n r_i](https://render.githubusercontent.com/render/math?math=%5Csum_%7Bi%3D1%7D%5En%20r_i) and letting the coordinator ensure that the combined commitment is a commitment to the public input amount with this randomness, but if this is problematic for the ACL security proof this can probably be proved in another ways.

From this protocol the user obtains ![n](https://render.githubusercontent.com/render/math?math=n) signatures for ![n](https://render.githubusercontent.com/render/math?math=n) commitments ![\zeta_{1.n}](https://render.githubusercontent.com/render/math?math=%5Czeta_%7B1.n%7D) in a way where the following properties hold:

- The coordinator can be sure ![\zeta_{1.n}](https://render.githubusercontent.com/render/math?math=%5Czeta_%7B1.n%7D) commit to the same values as ![C_n](https://render.githubusercontent.com/render/math?math=C_n) commitments.
- Neither ![\zeta_{1.n}](https://render.githubusercontent.com/render/math?math=%5Czeta_%7B1.n%7D) nor the obtained signatures are known by the coordinator.
- ![\zeta_{1.n}](https://render.githubusercontent.com/render/math?math=%5Czeta_%7B1.n%7D) and the obtained signatures are unlinkable to the ![C_n](https://render.githubusercontent.com/render/math?math=C_n) commitments.

## Output Registration

User can register a desired output for ![v_1](https://render.githubusercontent.com/render/math?math=v_1) by sending the coordinator

- ![\zeta_1.1 = \tilde{C}(v_1, r_1)](https://render.githubusercontent.com/render/math?math=%5Czeta_1.1%20%3D%20%5Ctilde%7BC%7D(v_1%2C%20r_1)).
- Some 0 commitments, but for simplicity let's say it only sends a single zero commitment: ![\zeta_1.3 = \tilde{C}(v_3, r_3)](https://render.githubusercontent.com/render/math?math=%5Czeta_1.3%20%3D%20%5Ctilde%7BC%7D(v_3%2C%20r_3)).
- Valid signatures for those commitments.
- The total amount ![v_1 + v_3 = v_1](https://render.githubusercontent.com/render/math?math=v_1%20%2B%20v_3%20%3D%20v_1), ~~and the sum of their blinding factors ![r_1 + r_3](https://render.githubusercontent.com/render/math?math=r_1%20%2B%20r_3)~~ (no, but see below).

Notice that, the first subscript of ![\zeta](https://render.githubusercontent.com/render/math?math=%5Czeta) is part of the variable name in the paper, while the second one denotes the index of the amount commitment.

# Amount Merging

The protocol is the same, except instead of only registering signed zero commitments at output registration, some of those commitments aren't zero, but maybe they were coming from different inputs.

# Unlinkability

Since the coordinator cannot recognize the unblinded signatures at output registration, it can only tell they are valid, unlinkability is guaranteed.

# Double Spend

Since the unblinded signatures are valid for single blinded commitments only, the coordinator can make sure one signature can only be used once.

**Comment by nothingmuch** [comment]
variable names should correspond to section 5 of https://cs.brown.edu/people/fbaldimt/papers/CCS13.pdf

an open question is how to set up the tag key ![z](https://render.githubusercontent.com/render/math?math=z) - seems like we probably just want a NUMS point?

for an intuition on the way the blinding works with the tag key, see [Abe's paper](https://www.researchgate.net/publication/221348138_A_Secure_Three-Move_Blind_Signature_Scheme_for_Polynomially_Many_Signatures).

it's noteworthy that the blinding/unlinkability is based on computational hardness, so if i'm not mistaken if the coordinator has a quantum computer or the underlying curve is broken then the coordinator would be able to de-anonymize users after the fact, but this doesn't seem like a concern since that would require bitcoin users to move all their funds anyway

finally, i don't understand the security proofs of ACL yet, but in the wasabi research club call about it Jonas mentioned the log of the group order needs to be larger than the security parameter. if this is only an issue for soundness then i don't think this is a problem, since a soundness break only leads to blameless DoS, and the coinjoin security model still applies WRT theft.

**Comment by nopara73** [comment]
> The user also needs to prove the sum - i think this can just be done revealing ![\sum_{i=1}^n r_i](https://render.githubusercontent.com/render/math?math=%5Csum_%7Bi%3D1%7D%5En%20r_i) and letting the coordinator ensure that the combined commitment is a commitment to the public input amount with this randomness, but if this is problematic for the ACL security proof this can probably proved otherwise.

AFAIK revealing the sum of the `r` values is enough.

**Comment by nothingmuch** [comment]
to prove the amount it's enough, what I'm not sure about is whether or not this might interferes with the provable security of ACL.

during registration you can reveal some of the attributes' if instead of proving their validity in zero knowledge, so i suspect this is not an issue, and intuitively revealing a sum says nothing about the individual summands so i suspect even if the proof of blindness relies on the randomness in the ![\zeta_1](https://render.githubusercontent.com/render/math?math=%5Czeta_1) commitment not being revealed to the adversary, revealing the sum of several of these would be OK.

but I want to be sure.

**Comment by nothingmuch** [comment]
i had a mistake in the derivation of `\product_{i} \zeta_{1.i}` terms - since the gamma term (blinding factor) applies to all generators, but the amount only applies to generator `h_0`, the this would require a combination of sub-amounts that has no 0 terms to avoid cancelling out the gamma terms.

so this means that we don't get signatures over commitments that are homomorphic in the amounts in a simple way.

however, the product of the zetas is still a Pedersen multi commitment, so i think we should be able to prove in zero knowledge that it commits to `h_0(\sum \gamma_i \v_i)` and that the sum of the `v_i` is the output amount being registered using a sigma protocol.

**Comment by nothingmuch** [comment]
About the unused message `m` and provable security: it seems it is the opposite, in [this paper](https://eprint.iacr.org/2019/1199.pdf) it is specifically removed, keeping only the attributes, in order to prove EUF-CMA security more generally (the ACL paper only proves it WRT sequential setting, whereas this variant is proven in concurrent one).

This paper also presents the ACL protocol with this very minor modification in additive notation, which is probably more readable for bitcoin audiences, where that seems to be standard.

**Comment by seresistvanandras** [comment]
Hereby a fix for the coin merging protocol is suggested by @nothingmuch and me. Again, we want to prove that the following relation holds between blinded commitments and a specially crafted point on the curve, ![$s$](https://render.githubusercontent.com/render/math?math=%24s%24). One lesson from the attack described above, that we need to constrain the user on how to select ![$s$](https://render.githubusercontent.com/render/math?math=%24s%24), otherwise she could lie about it.

![$\prod_{i \in S} \zeta_{1.i} \stackrel{?}{=} s^{v_{\mathrm{out}}}$](https://render.githubusercontent.com/render/math?math=%24%5Cprod_%7Bi%20%5Cin%20S%7D%20%5Czeta_%7B1.i%7D%20%5Cstackrel%7B%3F%7D%7B%3D%7D%20s%5E%7Bv_%7B%5Cmathrm%7Bout%7D%7D%7D%24)

Specifically the blinded commitments ![$\zeta_{1.i}$](https://render.githubusercontent.com/render/math?math=%24%5Czeta_%7B1.i%7D%24) have the following structure:
![$\prod_{i \in S} \zeta_{1.i} = \prod_{i \in S} h_1^{\gamma_i v_i} h_0^{\gamma_i R_i} g^{\gamma_i \mathrm{rnd}_i}$](https://render.githubusercontent.com/render/math?math=%24%5Cprod_%7Bi%20%5Cin%20S%7D%20%5Czeta_%7B1.i%7D%20%3D%20%5Cprod_%7Bi%20%5Cin%20S%7D%20h_1%5E%7B%5Cgamma_i%20v_i%7D%20h_0%5E%7B%5Cgamma_i%20R_i%7D%20g%5E%7B%5Cgamma_i%20%5Cmathrm%7Brnd%7D_i%7D%24).

Note that the user knows all the exponents present in the expression above, however user obviously does not know the discrete logarithms between the generators ![$g,h_0,h_1$](https://render.githubusercontent.com/render/math?math=%24g%2Ch_0%2Ch_1%24), because then the commitment scheme would not be computationally binding. The user can therefore create the following terms separately for each ![$\zeta_{1.i}$](https://render.githubusercontent.com/render/math?math=%24%5Czeta_%7B1.i%7D%24): ![$h_1^{\gamma_i v_i}$](https://render.githubusercontent.com/render/math?math=%24h_1%5E%7B%5Cgamma_i%20v_i%7D%24), ![h_0^{\gamma_i R_i} ](https://render.githubusercontent.com/render/math?math=h_0%5E%7B%5Cgamma_i%20R_i%7D%20), ![g^{\gamma_i \mathrm{rnd}_i}](https://render.githubusercontent.com/render/math?math=g%5E%7B%5Cgamma_i%20%5Cmathrm%7Brnd%7D_i%7D). Subsequently the user will prove that each of these terms contain ![$\gamma_i$](https://render.githubusercontent.com/render/math?math=%24%5Cgamma_i%24) in their exponent without disclosing anything about ![$\gamma_i$](https://render.githubusercontent.com/render/math?math=%24%5Cgamma_i%24). Put differently, user proves that the following tuples are Diffie-Hellman tuples: ![$(h_1,h^{\gamma_i}_1,h_1^{v_i},h_1^{\gamma_{i}v_{i}}),(h_0,h^{\gamma_i}_0,h_0^{R_i},h_0^{\gamma_{i}R_{i}}),(g,g^{\gamma_i},g^{\mathit{rnd}_i},g^{\gamma_{i}\mathit{rnd}_{i}})$](https://render.githubusercontent.com/render/math?math=%24(h_1%2Ch%5E%7B%5Cgamma_i%7D_1%2Ch_1%5E%7Bv_i%7D%2Ch_1%5E%7B%5Cgamma_%7Bi%7Dv_%7Bi%7D%7D)%2C(h_0%2Ch%5E%7B%5Cgamma_i%7D_0%2Ch_0%5E%7BR_i%7D%2Ch_0%5E%7B%5Cgamma_%7Bi%7DR_%7Bi%7D%7D)%2C(g%2Cg%5E%7B%5Cgamma_i%7D%2Cg%5E%7B%5Cmathit%7Brnd%7D_i%7D%2Cg%5E%7B%5Cgamma_%7Bi%7D%5Cmathit%7Brnd%7D_%7Bi%7D%7D)%24). Additionally user needs to convince coordinator that for each generator ![$h_0,h_1,g$](https://render.githubusercontent.com/render/math?math=%24h_0%2Ch_1%2Cg%24) the same ![$\gamma_i$](https://render.githubusercontent.com/render/math?math=%24%5Cgamma_i%24) was used in the exponent. This can be achieved by proving in zero-knowledge that the following tuples are Diffie-Hellman tuples: ![$(h_0,h_0^{\gamma_i},h_1,h_1^{\gamma_i}),(h_1,h_1^{\gamma_i},g,g^{\gamma_i})$](https://render.githubusercontent.com/render/math?math=%24(h_0%2Ch_0%5E%7B%5Cgamma_i%7D%2Ch_1%2Ch_1%5E%7B%5Cgamma_i%7D)%2C(h_1%2Ch_1%5E%7B%5Cgamma_i%7D%2Cg%2Cg%5E%7B%5Cgamma_i%7D)%24).

After revealing all these elements it is easy to verify the relation we want to prove to the coordinator by checking:

![$\prod_{i\in S}h_1^{v_i}=h_1^{\Sigma_{i\in S}v_i}=h_1^{v_\textit{out}}$](https://render.githubusercontent.com/render/math?math=%24%5Cprod_%7Bi%5Cin%20S%7Dh_1%5E%7Bv_i%7D%3Dh_1%5E%7B%5CSigma_%7Bi%5Cin%20S%7Dv_i%7D%3Dh_1%5E%7Bv_%5Ctextit%7Bout%7D%7D%24)

With this approach in place we do assume that an appropriate padding scheme is used for the values ![$v_i$](https://render.githubusercontent.com/render/math?math=%24v_i%24) to have a sufficiently large message space for the values ![$v_i$](https://render.githubusercontent.com/render/math?math=%24v_i%24). Otherwise coordinator could just figure out ![$h_1^{v_i}$](https://render.githubusercontent.com/render/math?math=%24h_1%5E%7Bv_i%7D%24) by brute-forcing the exponent. 

However two crucial questions remain which are not immediate IMO:

1. Do we harm blindness of ACL by revealing this many new elements in the Diffie-Hellman tuples?

2. Do we really achieve soundness with this fix? 

Maybe we do not harm neither 1) nor 2) but we additionally need to assume the Diffie-Hellman assumption for the soundness of the coin merging protocol and for the blindness of the ACL scheme to hold. We should try to prove blindness and soundness formally on our own and then see whether we can prove it with these modifications or not.

**Comment by nothingmuch** [comment]
i don't think there is a benefit to making that verification equation work on public values.

assuming soundness is addressed by the relations, i think that too should be done in zero knowledge, with only `v_out` as just a term in the relation being proved, so that the individual `h_1^x` as well as their product remain secret

**Comment by seresistvanandras** [comment]
> i don't think there is a benefit to making that verification equation work on public values.

Why? The only public value used is the registered output UTXO amount. All the rest is computationally unrecoverable assuming that the Discrete Logarithm Problem is hard in the underlying group.

> assuming soundness is addressed by these additional relations, i think the sum amount should also be done in zero knowledge, with only `v_out` as just a term in the relation being proved, so that the individual `h_1^x` as well as their product remain secret

I don't understand these arguments. If soundness is addressed then we are ready and don't need to work anymore. More precisely, if soundness is addressed then everything can be left and used as it is, it would be unnecessary to hide any more elements as soundness is already achieved. If you want all the ![$h_i^{v_i}$](https://render.githubusercontent.com/render/math?math=%24h_i%5E%7Bv_i%7D%24) terms remain secret, then the whole coin merging protocol will be significantly more complex and I'm not yet convinced that it is necessary to hide those terms. My bet is that soundness is already achieved but not 100% sure yet.

**Comment by nothingmuch** [comment]
hmm, maybe i misunderstood:

> After revealing all these elements it is easy to verify the relation we want to prove to the coordinator by checking:
> 
> ![$\prod_{i\in S}h_1^{v_i}=h_1^{\Sigma_{i\in S}v_i}=h_1^{v_\textit{out}}$](https://render.githubusercontent.com/render/math?math=%24%5Cprod_%7Bi%5Cin%20S%7Dh_1%5E%7Bv_i%7D%3Dh_1%5E%7B%5CSigma_%7Bi%5Cin%20S%7Dv_i%7D%3Dh_1%5E%7Bv_%5Ctextit%7Bout%7D%7D%24)

does this imply the coordinator computes the product out of individual `h_1^{v_i}` terms?

i understood yes (because otherwise padding the amounts would be unnecessary)

the reason i expect a single proof to be simpler is that verifying the sum should a single linear constraint on the `v_i` secret inputs which must be proven to be committed to anyway, whereas adding padding terms to rule out brute forcing makes the range proof relations much larger, each inner product would have an additional 128 multiplications in the inner product, and 128 multiplications checking that the bit vector components are in the subset `{0, 1} \subseteq Z_q`. technically the structure of the proof is as simple as the non-padded case, but the statements are much larger, and even with bulletproofs verification and proving time are still O(N)

**Comment by seresistvanandras** [comment]
> > After revealing all these elements it is easy to verify the relation we want to prove to the coordinator by checking:
> > ![$\prod_{i\in S}h_1^{v_i}=h_1^{\Sigma_{i\in S}v_i}=h_1^{v_\textit{out}}$](https://render.githubusercontent.com/render/math?math=%24%5Cprod_%7Bi%5Cin%20S%7Dh_1%5E%7Bv_i%7D%3Dh_1%5E%7B%5CSigma_%7Bi%5Cin%20S%7Dv_i%7D%3Dh_1%5E%7Bv_%5Ctextit%7Bout%7D%7D%24)
> 
> does this imply the coordinator computes the product out of individual `h_1^{v_i}` terms?
> 
> i understood yes (because otherwise padding the amounts would be unnecessary)

Yes, your understanding is correct!

> the reason i expect a single proof to be simpler is that verifying the sum should a single linear constraint on the `v_i` secret inputs which must be proven to be committed to anyway, whereas adding padding terms to rule out brute forcing makes the range proof relations much larger, each inner product would have an additional 128 multiplications in the inner product, and 128 multiplications checking that the bit vector components are in the subset `{0, 1} \subseteq Z_q`. technically the structure of the proof is as simple as the non-padded case, but the statements are much larger, and even with bulletproofs verification and proving time are still O(N)

As Bulletproofs are logarithmic in the range size, the added overhead is negligible IMO. For 32-bit range (without padding) we would have 5 group elements for the range proof, for a full range proof of 256-bit we would have 8 group elements.

**Comment by nothingmuch** [comment]
the proof size itself is negligibly larger, but constructing as well as verifying it is still O(N), it's just that the that this work is compressed to only a logarithmic sized verification equation in the end,

secondly, it feels a bit crude to me to use a computationally hiding padding scheme when we already have a perfectly binding commitment scheme for the same values

i'm still stuck on the homework phase, trying to figure out how to prove the sum of values committed to by a bunch of Pedersen commitments in a sigma protocol, but my understanding is that this isn't very complex, and should naturally compose with the per-credential proofs that relates the zeta terms to the individual amounts?

**Comment by seresistvanandras** [comment]
> the proof size itself is negligibly larger, but constructing as well as verifying it is still O(N), it's just that the that this work is compressed to only a logarithmic sized verification equation in the end,

I agree. If we can solve it without padding than we can save some dozens of exponentiations from the proof generation time. But still, I hardly doubt that this will be the protocol's bottleneck.

> secondly, it feels a bit crude to me to use a computationally hiding padding scheme when we already have a perfectly binding commitment scheme for the same values

Since the commitment scheme is perfectly binding, then [we cannot hope](https://crypto.stackexchange.com/questions/41822/why-cant-the-commitment-schemes-have-both-information-theoretic-hiding-and-bind) more than a computationally hiding scheme. So this is an inherent limitation we cannot circumvent.  

> i'm still stuck on the homework phase, trying to figure out how to prove the sum of values committed to by a bunch of Pedersen commitments in a sigma protocol, but my understanding is that this isn't very complex, and should naturally compose with the per-credential proofs that relates the zeta terms to the individual amounts?

Yeah, let's see if we can improve on this very elementary ZK proof system for coin merging. I agree that there should be a cleaner and more elegant way to achieve the same thing exploiting the nice properties of the blinded commitments.

**Comment by nothingmuch** [comment]
why is the commitment scheme perfectly binding? even ignoring gamma, the domain of Pedersen commitments in the attributes is `Z_q^2`, and the range is `G` of order `q`, and that's what we're trying to prove things about.

i agree for simple Pedersen hashing with generator `h1` the domain and range are of the same order, making it computationally hiding, but at least logically i see no reason why we need to disclose those values without the additional randomness mixed in, hence my desire to not expose these values,

**Comment by nothingmuch** [comment]
sorry, i had a very unfortunate brainfart, meant to write "we already have a perfectly hiding commitment scheme", since attributes are a Pedersen commitment.

just to be clear, given the choice for this application we should definitely favor perfect hiding to maintain privacy in case of any future crypto break

**Comment by nopara73** [comment]
I'm going through this issue sequentially, so things I'm mentioning here is probably addressed in later comments, anyway, I think everything should add up in the starting post of this issue, so I'm noting the logical problems:

> From this protocol the user obtains ![n](https://render.githubusercontent.com/render/math?math=n) signatures for ![n](https://render.githubusercontent.com/render/math?math=n) blinded commitments ![\zeta_{1.n}](https://render.githubusercontent.com/render/math?math=%5Czeta_%7B1.n%7D), which are not linkable to the ![C_n](https://render.githubusercontent.com/render/math?math=C_n) commitments, but the coordinator can be sure they commit to the same values (or attributes in ACL terms.)

Shouldn't it be more like: the user acquires `n` blinded signatures, which it unblinds such that they will be valid for `n` commitments those commit to the same values?

**Comment by nopara73** [comment]
https://github.com/zkSNACKs/WabiSabi/issues/30
