### ISSUE TITLE
Clarifying the Balance Proof

### ISSUE THREAD

**Issue by jonasnick** [zkSNACKs/WabiSabi#40]
Hey,

I read through d498f645a1611205feff541ec8f8d7410f4fc9e9 and I like the design. Great to see that KVACs + Pedersen Commitments of value and serial number attributes + rangeproofs in fact lead to a working and simple system. I'm looking forward to see this in practice - in particular because it's not only applicable to Chaumian Coinjoin, but can also be used to implement ecash.

- Section 4.3 (Over-spending prevention by balance proof) is a bit unclear to me. Shouldn't `pi^sum[1]` be the sum of differences between `M_vi` and `C_vi` `r`-values?
  Moreover, as specified it seems like the user would really send `sum(z_i)` to the coordinator instead of providing a zero knowledge proof the `prod(M_vi/C_vi)` relation. This would be a problem, because after seeing `sum_z`, the coordinator can for all subsets of `M_vi` he has previously seen, test whether `G_v^sum_z prod(M_vi) ?= prod(C_vi)` and therefore link `M_vi` issuances with the credential presentation.
- I didn't have a look at how Perfect Hiding would work
- nit: footnote 8 on "small values of k": where do the values come from?
- nit: 4.2.1. (Credential Presentation) mention that `t_i` is from credential

**Comment by nothingmuch** [comment]
the first bit about 4.3 - there's a mistake in the verification eqn, without addressing the 2nd issue, i think it should have been:

![$\prod_{i=1}^{k} C_{v_i} \stackrel{?}{=} {G_g}^{\pi^{\mathit{sum}}\[1\]}{G_h}^{\Delta_{v}} {C_{v_i}}^{\pi^{\mathit{sum}}\[2\]}$](https://render.githubusercontent.com/render/math?math=%24%5Cprod_%7Bi%3D1%7D%5E%7Bk%7D%20C_%7Bv_i%7D%20%5Cstackrel%7B%3F%7D%7B%3D%7D%20%7BG_g%7D%5E%7B%5Cpi%5E%7B%5Cmathit%7Bsum%7D%7D%5B1%5D%7D%7BG_h%7D%5E%7B%5CDelta_%7Bv%7D%7D%20%7BC_%7Bv_i%7D%7D%5E%7B%5Cpi%5E%7B%5Cmathit%7Bsum%7D%7D%5B2%5D%7D%24)

I think I must have messed it up when I changed everything from separate input/output registration to the the unified protocol. The coordinator can calculate the top of the RHS, compute `\prod M_i` directly because it doesn't see the `M_i`.

However, like you said because the message space is small this reveals enough for the coordinator to link together outputs by searching ![$\prod_{i \in S} M_{v_i} \stackrel{?}{=} {G_g}^{\pi^{\mathit{sum}}\[1\]} {G_h}^{v_{\mathrm{out}}} $](https://render.githubusercontent.com/render/math?math=%24%5Cprod_%7Bi%20%5Cin%20S%7D%20M_%7Bv_i%7D%20%5Cstackrel%7B%3F%7D%7B%3D%7D%20%7BG_g%7D%5E%7B%5Cpi%5E%7B%5Cmathit%7Bsum%7D%7D%5B1%5D%7D%20%7BG_h%7D%5E%7Bv_%7B%5Cmathrm%7Bout%7D%7D%7D%20%24) can link inputs and this statement should be proven in zero knowledge instead.

**Comment by nothingmuch** [comment]
sorry, i worked it out on paper, and yes, ![\pi^{\mathrm{sum}}](https://render.githubusercontent.com/render/math?math=%5Cpi%5E%7B%5Cmathrm%7Bsum%7D%7D) should be ![$ \left( \sum_{i=1}^k r^{\prime}_{v_i} - \sum_{i=1}^k r_{v_i}, \sum_{i=1}^k z_i \right)$](https://render.githubusercontent.com/render/math?math=%24%20%5Cleft(%20%5Csum_%7Bi%3D1%7D%5Ek%20r%5E%7B%5Cprime%7D_%7Bv_i%7D%20-%20%5Csum_%7Bi%3D1%7D%5Ek%20r_%7Bv_i%7D%2C%20%5Csum_%7Bi%3D1%7D%5Ek%20z_i%20%5Cright)%24) like you said, where `r'_{v_i}` is the `G_g` based randomness term of `C_{v_i}` and `r_{v_i}` is the one in `M_{v_i}`. I must have gotten the two `r`'s conflated when I wrote this.

As for fixing the privacy leak, I think it's a simple knowledge of exponent proof, ![$\mathrm{PK}\left(\left\{ (r) : {G_h}^{-\Delta_v} \prod_{i=1}^k \frac{M_{v_i}}{C_{v_i}} ={G_g}^{r} \right\}\right)$](https://render.githubusercontent.com/render/math?math=%24%5Cmathrm%7BPK%7D%5Cleft(%5Cleft%5C%7B%20(r)%20%3A%20%7BG_h%7D%5E%7B-%5CDelta_v%7D%20%5Cprod_%7Bi%3D1%7D%5Ek%20%5Cfrac%7BM_%7Bv_i%7D%7D%7BC_%7Bv_i%7D%7D%20%3D%7BG_g%7D%5E%7Br%7D%20%5Cright%5C%7D%5Cright)%24) where ![$r = \sum_{i=1}^k r_{v_i} - r^\prime_{v_i}$](https://render.githubusercontent.com/render/math?math=%24r%20%3D%20%5Csum_%7Bi%3D1%7D%5Ek%20r_%7Bv_i%7D%20-%20r%5E%5Cprime_%7Bv_i%7D%24). if i'm not mistaken that's how it's done in CT just as an ECDSA signature instead of Schnorr identity?

@seresistvanandras

**Comment by nothingmuch** [comment]
it can't just be a signature because i forgot that the proof also needs to cover the `z` term. anyway, here's my attempt at redoing 4.3:


![image](https://user-images.githubusercontent.com/14242/83309068-d7ef4e00-a1f7-11ea-87c3-eb7041d53d8a.png)

**Comment by jonasnick** [comment]
@nothingmuch looks good to me now :+1:

**Comment by lontivero** [comment]
I think there is a problem with the generators.
![IMG_20200604_153954](https://user-images.githubusercontent.com/127973/83798228-54f84880-a67a-11ea-89f3-99405904dca9.jpg)

**Comment by nothingmuch** [comment]
cancelling out `M_{v_i}` from `C_{v_i}` is not right because those refer to different credentials, `M_{v_i}` are the attributes for the credentials being requested, and C_{v_i} are the ones being presented. Combined with `G^{\Delta_v}`, the amounts should cancel which results in `G_h^0`.

we should find a better notation for these, it's really terrible, created #46

**Comment by lontivero** [comment]
Thank you. Now it finally make sense to me (what means the code works ;)

```c#
var B = (request.DeltaValue * Generators.Gh) +
	Sum(C_v0, C_v1, C_v2, C_v3) +
	Sum(M_v0, M_v1, M_v2, M_v3).Negate(); 

VerifyProofOfBalance(B, request.BalanceProof);  // True
```
