### ISSUE TITLE
document structure improvements

### ISSUE THREAD

**Issue by nothingmuch** [zkSNACKs/WabiSabi#51]
- the terminology and definitions section in the protocol overview does not directly support the subsequent sections, and should probably be moved after scheduling, or just merged with the registration section
- the preliminaries section and the terminology and definitions subsection in protocol overview are not very consistently formatted with the rest of the document.

**Comment by nopara73** [comment]
I'm not a fan of this dictionary approach. I didn't say this before, because you seem to like it, but since you're having issues with it, maybe we should remove it altogether as you suggested in your first point. IMO this "let's put down definitions and expect people to memorize them and magically they'll know what we're talking about in later sections" is a lazy approach that does not map how humans understand anything. It'd be different if you're listing stuff to guide the implementors, but most of the time it isn't the case and it is not the case here either.

**Comment by nothingmuch** [comment]
i moved the terminology stuff around a bit, i also have a version of that commit which is independent of the optimization branch, but it was a simpler change there
